apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-bgzj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-bgzj
    app.kubernetes.io/part-of: test-app-hraa
  name: docker-devfile-sample-hello-world-bgzj
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-bgzj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-bgzj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-pbym-tenant/test-app-hraa/docker-devfile-sample-hello-world-bgzj@sha256:2d53d52e00f70c7038f3b273f1b74d77d0ee25df711c50f56c4c5dd72baab741
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
